### ISSUE TITLE
Clarification--CheckID does not have associated TTL

### ISSUE THREAD

**Issue by nandhusriram** [OrbitzWorldwide/consul-client#100]
I have a Ttl scheduler running every 30s ,throwing NPE com.orbitz.consul.NotRegisteredException: null
	at com.orbitz.consul.AgentClient.check(AgentClient.java:404)
	at com.orbitz.consul.AgentClient.checkTtl(AgentClient.java:420)
	at com.orbitz.consul.AgentClient.pass(AgentClient.java:427)
	at com.assurant.inc.transformation.consul.TtlScheduler.heartbeatServices(TtlScheduler.java:58).

FYI http health check is passing.

**Comment by rickfast** [comment]
I'll take a look. Can you post a snippet of your code setting up the client?

**Comment by nandhusriram** [comment]
Looks like it needed cleanup  from consul , once I deregistered the services and registered back , it worked . Thanks
