### ISSUE TITLE
getKeys() causes an exception to be thrown

### ISSUE THREAD

**Issue by antoniobeyah** [OrbitzWorldwide/consul-client#131]
when using 0.12.0 and calling getKeys, this exception is thrown.  Rolling back to 0.10.0 works properly.

Here is the result of a curl:
/v1/kv/seed_jobs%2F?keys=true
-> curl localhost:8500/v1/kv/seed_jobs%2F?keys=true
["seed_jobs/","seed_jobs/job1/","seed_jobs/job1/git_url","seed_jobs/job2/","seed_jobs/job3/"]

Here is the code:
```
    def consul = Consul.builder().build()
    def kv = consul.keyValueClient()
    def keys = kv.getKeys("seed_jobs/")

    println "RUNNING SCRIPT"
    println "Keys: $keys"
```

```
Exception in thread "main" com.orbitz.consul.ConsulException: Consul request failed
> Buildiat com.orbitz.consul.util.Http.extract(Http.java:21)
	at com.orbitz.consul.KeyValueClient.getKeys(KeyValueClient.java:268)
	at com.orbitz.consul.KeyValueClient$getKeys.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at LoadJobs.main(LoadJobs.groovy:23)
Caused by: com.orbitz.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class com.orbitz.consul.model.kv.ImmutableValue$Json] from String value ('seed_jobs/'); no single-String constructor/factory method
 at [Source: java.io.InputStreamReader@6a6afff2; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
	at com.orbitz.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at com.orbitz.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:992)
	at com.orbitz.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:316)
	at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:288)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1200)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:144)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1193)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:144)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.orbitz.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.orbitz.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at com.orbitz.retrofit.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at com.orbitz.retrofit.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at com.orbitz.retrofit.ServiceMethod.toResponse(ServiceMethod.java:116)
	at com.orbitz.retrofit.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at com.orbitz.retrofit.OkHttpCall.execute(OkHttpCall.java:174)
	at com.orbitz.consul.util.Http.extract(Http.java:19)
	... 6 more
:seedjobs:runScript FAILED
```

**Comment by rickfast** [comment]
Just fixed this a few days ago: 5f4214c7f11b14a7c113f3d6b5886b28bf5d5b02

I'll release today

**Comment by rickfast** [comment]
```0.12.1``` has the fix

**Comment by antoniobeyah** [comment]
thanks rick, that was fast.  rickfast.

**Comment by rickfast** [comment]
:)
