### ISSUE TITLE
ConsulCache error

### ISSUE THREAD

**Issue by xieyanze** [OrbitzWorldwide/consul-client#137]
when serviceHealthCache add Listener
[OkHttp http://192.168.21.171:8500/v1/health/service/Demo-QuickStartService?index=8&wait=20s&passing=true] ERROR com.orbitz.consul.cache.ConsulCache - Error getting response from consul. will retry in 10 SECONDS

**Comment by rickfast** [comment]
Are you running Consul in Docker? Can you successfully curl that endpoint from the command line?

**Comment by xieyanze** [comment]
not running docker.
 when this exception exception happened, can open this url in web browser successfully.
10:01:06.342 [OkHttp http://192.168.21.171:8500/v1/health/service/Demo-QuickStartService?index=3857&wait=20s&passing=true] ERROR com.orbitz.consul.cache.ConsulCache - Error getting response from consul. will retry in 10 SECONDS
java.net.SocketTimeoutException: timeout
	at com.orbitz.okio.Okio$3.newTimeoutException(Okio.java:207)
	at com.orbitz.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at com.orbitz.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at com.orbitz.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at com.orbitz.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at com.orbitz.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.orbitz.okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at com.orbitz.okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at com.orbitz.okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
	at com.orbitz.okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
	at com.orbitz.okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at com.orbitz.okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at com.orbitz.okhttp3.RealCall.getResponse(RealCall.java:241)
	at com.orbitz.okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at com.orbitz.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at com.orbitz.okhttp3.RealCall.access$100(RealCall.java:30)
	at com.orbitz.okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at com.orbitz.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.orbitz.okio.Okio$2.read(Okio.java:139)
	at com.orbitz.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 18 common frames omitted

**Comment by xieyanze** [comment]
not running docker.
[root@APP-Nginx ~]# curl http://192.168.21.171:8500/v1/health/service/Demo-QuickStartService?index=3873&wait=20s&passing=true
[1] 14338
[2] 14339

can not successfully this endpoint. but this endpoint can opened in web browser successfully

**Comment by matevarga** [comment]
The cache works, the problem is just the logging. If the watched values don't change then it logs an error before re-scheduling the check. I might send in a PR.

**Comment by zjfplayer** [comment]
the reason is in parent class `ConsulCache.ConsulCache(
            Function<V, K> keyConversion,
            CallbackConsumer<V> callbackConsumer,
            final long backoffDelayQty,
            final TimeUnit backoffDelayUnit) ` ,it will call the method `@Override
            public void onFailure(Throwable throwable) {

                if (!isRunning()) {
                    return;
                }
                LOGGER.error(String.format("Error getting response from consul. will retry in %d %s", backoffDelayQty, backoffDelayUnit), throwable);

                executorService.schedule(new Runnable() {
                    @Override
                    public void run() {
                        runCallback();
                    }
                }, backoffDelayQty, backoffDelayUnit);
            }`
the command I run consul is `consul agent -bind=192.168.1.130 -http-port=8500 -data-dir=e:\consul_0.6.4_windows_amd64 -ui -server -bootstrap`, and the output is `==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: Windows is not recommended as a Consul server. Do not use in production.
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'zhengjiefeng'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
      Cluster Addr: 192.168.1.130 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>`
I don`t know how to resolve this problem.

**Comment by zjfplayer** [comment]
And the "onFailure" method's parameter throwable throws `org.eclipse.debug.core.DebugException: com.sun.jdi.ClassNotLoadedException: Type has not been loaded occurred while retrieving component type of array.`

**Comment by zjfplayer** [comment]
My test code is your test code in java file which named "ConsulCacheTest" in package "src\test\java\com\orbitz\consul\cache",the method code is  `@Test
    public void testListeners() throws Exception {
        KeyValueClient kvClient = client.keyValueClient();
        String root = UUID.randomUUID().toString();

        KVCache nc = KVCache.newCache(
                kvClient, root, 10
        );

        final List<Map<String, Value>> events = new ArrayList<Map<String, Value>>();
        nc.addListener(new ConsulCache.Listener<String, Value>() {
            @Override
            public void notify(Map<String, Value> newValues) {
                events.add(newValues);
            }
        });

        nc.start();

        if (!nc.awaitInitialized(1, TimeUnit.SECONDS)) {
            fail("cache initialization failed");
        }

        for (int i = 0; i < 5; i++) {
            kvClient.putValue(root + "/" + i, String.valueOf(i));
            Thread.sleep(100);
        }

        assertEquals(5, events.size());

        for (int i = 0; i < 5; i++) {

            Map<String, Value> map = events.get(i);
            assertEquals(i + 1, map.size());
            for (int j = 0; j < i; j++) {
                String keyStr = "" + j;
                String valStr = keyStr;
                assertEquals(valStr, map.get(keyStr).getValueAsString().get());
            }
        }
        kvClient.deleteKeys(root);

    }`

**Comment by xieyanze** [comment]
thanks
