### ISSUE TITLE
java.lang.IllegalStateException: Unable to extract the trust manager on com.orbitz.okhttp3.internal.Platform, sslSocketFactory is class sun.security.ssl.SSLSocketFactoryImpl

### ISSUE THREAD

**Issue by kunnu** [OrbitzWorldwide/consul-client#138]
I am getting below exception while building Consul client. 

`Consul.builder().build();`

`Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on com.orbitz.okhttp3.internal.Platform@137ed968, sslSocketFactory is class sun.security.ssl.SSLSocketFactoryImpl
	at com.orbitz.okhttp3.OkHttpClient.<init>(OkHttpClient.java:187)
	at com.orbitz.okhttp3.OkHttpClient.<init>(OkHttpClient.java:60)
	at com.orbitz.okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
	at com.orbitz.consul.Consul$Builder.createRetrofit(Consul.java:424)
	at com.orbitz.consul.Consul$Builder.build(Consul.java:368)`

Am I missing anything here. Could you please help.

**Comment by dkubiak** [comment]
It;s problem with lib okhttp  https://github.com/square/okhttp/issues/2323

**Comment by kunnu** [comment]
Thanks ! :+1:
