### ISSUE TITLE
Health client not compatible with consul 0.5.2

### ISSUE THREAD

**Issue by YulawOne** [OrbitzWorldwide/consul-client#149]
```
Caused by: com.orbitz.consul.ConsulException: Consul request failed
	at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:49)
	at com.orbitz.consul.HealthClient.getAllServiceInstances(HealthClient.java:417)
	at com.orbitz.consul.HealthClient.getAllServiceInstances(HealthClient.java:372)
	at com.orbitz.consul.HealthClient$getAllServiceInstances.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at consul.pick-only-changed-test$_run_closure3.doCall(pick-only-changed-test.groovy:53)
	at consul.pick-only-changed-test$_run_closure3.doCall(pick-only-changed-test.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:53)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:105)
	at com.sun.proxy.$Proxy30.call(Unknown Source)
	at rx.Scheduler$Worker$1.call(Scheduler.java:136)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: com.orbitz.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.orbitz.consul.model.health.ImmutableNode] value failed (java.lang.IllegalStateException): Cannot build Node, some of required attributes are not set [taggedAddresses]
 at [Source: java.io.InputStreamReader@72aceb18; line: 1, column: 58] (through reference chain: java.util.ArrayList[0]->com.orbitz.consul.model.health.Json["Node"])
	at com.orbitz.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:262)
	at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:445)
	at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:464)
	at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:502)
	at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:265)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1119)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.orbitz.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.orbitz.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1119)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.orbitz.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.orbitz.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.orbitz.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.orbitz.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at com.orbitz.retrofit.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at com.orbitz.retrofit.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at com.orbitz.retrofit.ServiceMethod.toResponse(ServiceMethod.java:117)
	at com.orbitz.retrofit.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at com.orbitz.retrofit.OkHttpCall.execute(OkHttpCall.java:174)
	at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:47)
	... 29 more
Caused by: java.lang.IllegalStateException: Cannot build Node, some of required attributes are not set [taggedAddresses]
	at com.orbitz.consul.model.health.ImmutableNode$Builder.build(ImmutableNode.java:300)
	at com.orbitz.consul.model.health.ImmutableNode.fromJson(ImmutableNode.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.orbitz.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:115)
	at com.orbitz.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:486)
	... 52 more

```

**Comment by rickfast** [comment]
fixed via 6ff6875c1cb989c6a54b5098bbaff7dffc638717
