### ISSUE TITLE
ConsulCache say that "Error getting response from consul. will retry in 10 SECONDS" but retry is within the same second 09:16:34

### ISSUE THREAD

**Issue by dantheman46** [OrbitzWorldwide/consul-client#151]
09:16:34,774 ERROR [com.orbitz.consul.cache.ConsulCache] (OkHttp http://localhost:8500/...) Error getting response from consul. will retry in 10 SECONDS: com.orbitz.consul.ConsulException: Consul cluster has no elected leader
	at com.orbitz.consul.cache.ConsulCache$1.onComplete(ConsulCache.java:86) [consul-client-0.12.6.jar:]
	at com.orbitz.consul.util.Http$1.onResponse(Http.java:63) [consul-client-0.12.6.jar:]
	at com.orbitz.retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:132) [consul-client-0.12.6.jar:]
	at com.orbitz.retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:111) [consul-client-0.12.6.jar:]
	at com.orbitz.okhttp3.RealCall$AsyncCall.execute(RealCall.java:133) [consul-client-0.12.6.jar:]
	at com.orbitz.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [consul-client-0.12.6.jar:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_91]

09:16:34,821 ERROR [com.orbitz.consul.cache.ConsulCache] (OkHttp http://localhost:8500/...) Error getting response from consul. will retry in 10 SECONDS: com.orbitz.consul.ConsulException: Consul cluster has no elected leader
	at com.orbitz.consul.cache.ConsulCache$1.onComplete(ConsulCache.java:86) [consul-client-0.12.6.jar:]
	at com.orbitz.consul.util.Http$1.onResponse(Http.java:63) [consul-client-0.12.6.jar:]
	at com.orbitz.retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:132) [consul-client-0.12.6.jar:]
	at com.orbitz.retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:111) [consul-client-0.12.6.jar:]
	at com.orbitz.okhttp3.RealCall$AsyncCall.execute(RealCall.java:133) [consul-client-0.12.6.jar:]
	at com.orbitz.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [consul-client-0.12.6.jar:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_91]

**Comment by dantheman46** [comment]
Sorry I have got two caches because of two datacenters
