### ISSUE TITLE
java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by thomas-oo** [OrbitzWorldwide/consul-client#239]
Socket closed exception occuring after executing various client queries or after some time has passed between queries. It happens to catalogclient, agentclient, etc. Do I need to reload these clients or something? I am not sure why the sockets are closing.

**Comment by thomas-oo** [comment]
[Stack trace](https://gist.github.com/thomas-oo/51fcd4010f3e5ba258b18aa02486dfff)
`java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[na:1.8.0_131]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_131]
	at okio.Okio$2.read(Okio.java:140) ~[okio-1.8.0.jar:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238) ~[okio-1.8.0.jar:na]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) ~[okio-1.8.0.jar:na]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) ~[okio-1.8.0.jar:na]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) ~[okio-1.8.0.jar:na]
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184) ~[okhttp-3.3.0.jar:na]
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125) ~[okhttp-3.3.0.jar:na]
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775) ~[okhttp-3.3.0.jar:na]
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86) ~[okhttp-3.3.0.jar:na]
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760) ~[okhttp-3.3.0.jar:na]
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613) ~[okhttp-3.3.0.jar:na]
	at okhttp3.RealCall.getResponse(RealCall.java:244) ~[okhttp-3.3.0.jar:na]
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201) ~[okhttp-3.3.0.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163) ~[okhttp-3.3.0.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:57) ~[okhttp-3.3.0.jar:na]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) ~[retrofit-2.1.0.jar:na]
	at com.orbitz.consul.util.Http.extractConsulResponse(Http.java:52) ~[consul-client-0.15.0.jar:na]
	at com.orbitz.consul.CatalogClient.getServices(CatalogClient.java:109) ~[consul-client-0.15.0.jar:na]
at com.orbitz.consul.CatalogClient.getServices(CatalogClient.java:97) ~[consul-client-0.15.0.jar:na]`

**Comment by thomas-oo** [comment]
And when I visit the ui of the consul agent, it is stuck at loading

**Comment by thomas-oo** [comment]
In [com.orbitz.consul.util.Http.extractConsulResponse](https://github.com/OrbitzWorldwide/consul-client/blob/master/src/main/java/com/orbitz/consul/util/Http.java): shouldn't response.body.close be called? This is from a quick search online that the practice is to close the stream. This is probably why the consul agent is running out of sockets to establish connections to?

**Comment by thomas-oo** [comment]
Unrelated problem was causing this error, closing

**Comment by Abrar-Snap** [comment]
> Unrelated problem was causing this error, closing

Can I know what was causing this socket closed exception?
