### ISSUE TITLE
Getting an Exception when a value is set in Consul?

### ISSUE THREAD

**Issue by aash73** [OrbitzWorldwide/consul-client#241]
Hello there, 
I wrote a simple java client which connects to Consul running on local host, gets a KeyValueClient out and then try to retrieve the value of a key. If the key is NOT set in Consul, everything is fine (i.e. no exception), but if the value is there, I get an exception. Here is the exception:
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.primitives.UnsignedLongs.decode(Ljava/lang/String;)J
	at com.orbitz.consul.util.UnsignedLongDeserializer.deserialize(UnsignedLongDeserializer.java:19)
	at com.orbitz.consul.util.UnsignedLongDeserializer.deserialize(UnsignedLongDeserializer.java:15)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1119)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at com.orbitz.consul.util.Http.extract(Http.java:24)
	at com.orbitz.consul.KeyValueClient.getValue(KeyValueClient.java:77)
	at com.orbitz.consul.KeyValueClient.getValue(KeyValueClient.java:62)
	at UCCConsulClient1.getStringValue(UCCConsulClient1.java:98)
	at ConsulTest.main(ConsulTest.java:21)

What I am doing is the following:
`			Optional<Value> ret = m_kvClient.getValue(aKey);
			if (!ret.isPresent()) {
				System.out.println("Response for Key: " + aKey + ", is null");
				return (null);
			}
			else {
				String value = ret.get().getValueAsString().get();
				System.out.println("getStringValue(): Key: " + aKey + ", Value: " + value);
				return (value);
			}
`

Any ideas please?
Thanks

**Comment by aash73** [comment]
Hello there, 
I also tried the following,
			String value = m_kvClient.getValueAsString(aKey).get();
			System.out.println("getStringValueEx(): Key: " + aKey + ", Value: " + value);
			return (value);
throws the same exception as before. this code is from the code example in the README file. I can successfully insert a value using "putValue()" method on the KeyValueClient, right before I call the getValue() method.
Not sure what's going on and/or what am I doing wrong.
Any help would be greatly appreciated.
regards
-Asim

**Comment by aash73** [comment]
Folks, I am pretty much stuck. Any help would be greatly appreciated. 
Thanks

**Comment by rickfast** [comment]
Looks like a version mismatch with Guava. You likely have a different version on your classpath that doesn't have the decode method

**Comment by aash73** [comment]
Rick, I do appreciate your response. Thanks.  I am using Maven to build my test client. Here is what the dependency looks like:
      <dependency>
            <groupId>com.orbitz.consul</groupId>
            <artifactId>consul-client</artifactId>
            <version>0.15.0</version>
      </dependency>  
      
      <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>11.0.2</version>
      </dependency>
   </dependencies>
    <repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>

Am i suppose to be using a different version of Guava? 
Thanks in advance for you help.

**Comment by aash73** [comment]
Rick, I do appreciate your response. Thanks. I am using Maven to build my test client. Here is what the dependency looks like:
`      <dependency>
            <groupId>com.orbitz.consul</groupId>
            <artifactId>consul-client</artifactId>
            <version>0.15.0</version>
      </dependency>  
      
      <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>11.0.2</version>
      </dependency>
   </dependencies>
    <repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>
`

Is there a different version of Guava I need to have?
Thanks in advance

**Comment by aash73** [comment]
Ah, getting the newest version (i.e. 22.0) of guava resolved it. 
THANK YOU Rick for the help. Appreciate it.
one other question. Do we have API documentation (unofficial is also OK) please?

**Comment by rickfast** [comment]
Consul API docs are at consul.io and this library has published Javadocs in Maven Central
