### ISSUE TITLE
failed to parse agent config with consul 1.0.0

### ISSUE THREAD

**Issue by philippeu** [OrbitzWorldwide/consul-client#267]
consul-client 0.16.5 failed to parse agent configuration with lastest consul version 1.0.0
`agentClient().getAgent().getConfig()`

The following execption is thrown
`Caused by: java.lang.IllegalStateException: Cannot build Config, some of required attributes are not set [bootstrap, dataDir, dnsRecursor, domain, logLevel, clientAddr, bindAddr, advertiseAddr, ports, leaveOnTerm, skipLeaveOnInt, protocol, enableDebug, verifyIncoming, verifyOutgoing, caFile, certFile, keyFile, pidFile, enableSyslog, rejoinAfterLeave]
	at com.orbitz.consul.model.agent.ImmutableConfig$Builder.build(ImmutableConfig.java:2564)
	at com.orbitz.consul.model.agent.ImmutableConfig.fromJson(ImmutableConfig.java:2047)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:114)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:516)`

**Comment by rickfast** [comment]
It appears there are a number of breaking changes in Consul 1.0. I will address these sometime in the coming week

**Comment by rickfast** [comment]
fixed by 0f4ea7aa220289ad2a76512a5e6652ee45b90282. Thanks @Furcube !
