### ISSUE TITLE
AgentClient.ping: "java.io.EOFException: \n not found: size=0 content=…"

### ISSUE THREAD

**Issue by bitsofinfo** [OrbitzWorldwide/consul-client#282]
Getting this talking to consu 0.7.5 and 1.x+  on 8500 (non-ssl) 

Using either 0.13.2 or 0.17.1

```
docker run -p 8500:8500 consul:0.7.5 agent -server -bootstrap-expect 1 -data-dir /tmp/consul
```

OR

```
docker run -p 8500:8500 consul:latest agent -server -bootstrap-expect 1 -data-dir /tmp/consul
```

```
Caused by: java.io.IOException: unexpected end of stream on okhttp3.Address@d559ffe9
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:199)
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
        at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
        at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
        at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
        at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
        at okhttp3.RealCall.getResponse(RealCall.java:244)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
        at okhttp3.RealCall.execute(RealCall.java:57)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
        at com.orbitz.consul.AgentClient.ping(AgentClient.java:58)
        ... 49 more
Caused by: java.io.EOFException: \n not found: size=0 content=…
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
        ... 60 more
```

**Comment by rickfast** [comment]
On vacation til week after next, so I won’t be able to look at this until then. PRs welcome
