### ISSUE TITLE
null kv values

### ISSUE THREAD

**Issue by gjesse** [OrbitzWorldwide/consul-client#48]
Calling something like $ ```curl -X PUT "127.0.0.1:8500/v1/kv/put/a/null/val"```
 is valid for consul, creates a key representation like so:
 
```
 [
  {
    "CreateIndex": 427,
    "ModifyIndex": 427,
    "LockIndex": 0,
    "Key": "put/a/null/val",
    "Flags": 0,
    "Value": null
  }
]
```

 however the cxf library doesn't allow null entity bodies. I tried a few different versions (they are up to 3.1.1 now) but they all failed with a similar stack trace:
    
```
    java.lang.NullPointerException
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:882)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:865)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:428)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1636)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.put(WebClient.java:1591)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.put(InvocationBuilderImpl.java:165)
	at com.orbitz.consul.KeyValueClient.putValue(KeyValueClient.java:224)
	at com.orbitz.consul.KeyValueClient.putValue(KeyValueClient.java:192)
	at com.orbitz.consul.KeyValueTests.putNullValue(KeyValueTests.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

example test: 

``` @Test
    public void putNullValue() {


        Boolean foo = null;

        Consul client = Consul.newClient();
        KeyValueClient keyValueClient = client.keyValueClient();
        String key = UUID.randomUUID().toString();
        assertTrue(keyValueClient.putValue(key, null));
        Value received = keyValueClient.getValue(key).get();
        assertFalse(received.getValue().isPresent());

        keyValueClient.deleteKey(key);
    }
```

**Comment by egulias** [comment]
I think `null` in your test should be a `String` and not the type, since the request you put as an example is interpreting `null` as a `String` not as a "null" value.

**Comment by gjesse** [comment]
It doesn't make any difference - null is not a type. I think what you're saying is something like this ??

```
    @Test
    public void putNullValue() {

        String val = null;
        Consul client = Consul.newClient();
        KeyValueClient keyValueClient = client.keyValueClient();
        String key = UUID.randomUUID().toString();

        assertTrue(keyValueClient.putValue(key, val));

        Value received = keyValueClient.getValue(key).get();
        assertFalse(received.getValue().isPresent());

        keyValueClient.deleteKey(key);
    }
```

which has exactly the same result

**Comment by gjesse** [comment]
I looked this a bit more and I think I have a reasonable solution

**Comment by egulias** [comment]
Well, I was thinking that what you send with curl is more similar to
String val = "null";
If I wanted to send a curl with null value I'd send
curl -X PUT "127.0.0.1:8500/v1/kv/put/a/key/"
That's a null value for `key` or
curl -X PUT "127.0.0.1:8500/v1/kv/put/a//val".
Because I think `null` in the request is translated to the String " null"
no to a null value.

**Comment by gjesse** [comment]
"null" as a string is not the same as a null value, and consul does not treat it as such. 

For example, put an empty body request vs "null" as the value and see that the output is not the same

```
(default)jesse@Jesse:~/Projects/open-source/consul-client (fix-tests)
$ http 127.0.0.1:8500/v1/kv/foo
HTTP/1.1 200 OK
Content-Length: 88
Content-Type: application/json
Date: Tue, 11 Aug 2015 18:55:14 GMT
X-Consul-Index: 169
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

[
    {
        "CreateIndex": 167, 
        "Flags": 0, 
        "Key": "foo", 
        "LockIndex": 0, 
        "ModifyIndex": 169, 
        "Value": null
    }
]

(default)jesse@Jesse:~/Projects/open-source/consul-client (fix-tests)
$ echo "null" | http PUT 127.0.0.1:8500/v1/kv/foo
HTTP/1.1 200 OK
Content-Length: 4
Content-Type: application/json
Date: Tue, 11 Aug 2015 18:55:25 GMT

true

(default)jesse@Jesse:~/Projects/open-source/consul-client (fix-tests)
$ http 127.0.0.1:8500/v1/kv/foo
HTTP/1.1 200 OK
Content-Length: 94
Content-Type: application/json
Date: Tue, 11 Aug 2015 18:55:28 GMT
X-Consul-Index: 171
X-Consul-Knownleader: true
X-Consul-Lastcontact: 0

[
    {
        "CreateIndex": 167, 
        "Flags": 0, 
        "Key": "foo", 
        "LockIndex": 0, 
        "ModifyIndex": 171, 
        "Value": "bnVsbAo="
    }
]
```

**Comment by gjesse** [comment]
closing this, should be fixed now
