### ISSUE TITLE
Spring boot application throws Exception - FYI

### ISSUE THREAD

**Issue by nickspat** [OrbitzWorldwide/consul-client#83]
javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class java.util.List, ContentType: application/json.
	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:433) ~[cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:378) ~[cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:325) ~[cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:313) ~[cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
	at com.orbitz.consul.util.ClientUtil.readResponse(ClientUtil.java:197) ~[consul-client-0.9.12.jar:na]
	at com.orbitz.consul.util.ClientUtil.consulResponse(ClientUtil.java:167) ~[consul-client-0.9.12.jar:na]
	at com.orbitz.consul.util.ClientUtil.access$000(ClientUtil.java:28) ~[consul-client-0.9.12.jar:na]
	at com.orbitz.consul.util.ClientUtil$1.completed(ClientUtil.java:134) [consul-client-0.9.12.jar:na]
	at com.orbitz.consul.util.ClientUtil$1.completed(ClientUtil.java:129) [consul-client-0.9.12.jar:na]
	at org.apache.cxf.jaxrs.client.JaxrsClientCallback.handleResponse(JaxrsClientCallback.java:77) [cxf-rt-rs-client-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.client.WebClient.handleAsyncResponse(WebClient.java:1025) [cxf-rt-rs-client-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.client.WebClient.access$100(WebClient.java:81) [cxf-rt-rs-client-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.client.WebClient$ClientAsyncResponseInterceptor.handleMessage(WebClient.java:1296) [cxf-rt-rs-client-3.0.3.jar:3.0.3]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.client.ClientMessageObserver.onMessage(ClientMessageObserver.java:56) [cxf-rt-rs-client-3.0.3.jar:3.0.3]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1638) [cxf-rt-transports-http-3.0.3.jar:3.0.3]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1145) [cxf-rt-transports-http-3.0.3.jar:3.0.3]
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$3.run(AutomaticWorkQueueImpl.java:428) [cxf-core-3.0.3.jar:3.0.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$AWQThreadFactory$1.run(AutomaticWorkQueueImpl.java:353) [cxf-core-3.0.3.jar:3.0.3]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to narrow type [collection type; class com.google.common.collect.ImmutableList, contains [simple type, class com.orbitz.consul.model.health.HealthCheck]] with concrete-type annotation (value java.util.ArrayList), method 'checks': Class java.util.ArrayList is not assignable to com.google.common.collect.ImmutableList
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:1782) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:731) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:510) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:229) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:142) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:466) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectReader._findRootDeserializer(ObjectReader.java:1749) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1465) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:810) ~[jackson-jaxrs-base-2.5.3.jar:2.5.3]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1325) ~[cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:369) ~[cxf-rt-frontend-jaxrs-3.0.3.jar:3.0.3]
	... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class java.util.ArrayList is not assignable to com.google.common.collect.ImmutableList
	at com.fasterxml.jackson.databind.JavaType._assertSubclass(JavaType.java:466) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.JavaType.narrowBy(JavaType.java:149) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:315) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:1780) ~[jackson-databind-2.6.3.jar:2.6.3]
	... 40 common frames omitted

**Comment by tolwi** [comment]
#78

**Comment by rickfast** [comment]
fixed by ac86124866c7c0f324d26707c4c30d5d43162802

**Comment by rickfast** [comment]
this fix is available now in ```0.9.14```
