### ISSUE TITLE
consul.catalogClient().getService("consul") throws exception

### ISSUE THREAD

**Issue by alladivasu** [OrbitzWorldwide/consul-client#92]
I am trying to use client code to get service CatalogService object but I get a InstantiationExceotion.

Code Snippet:
Consul consul = Consul.builder().build(); // connect to Consul on localhost
ConsulResponse<List<CatalogService>> catalogServices = consul.catalogClient().getService("consul");

I can get service details using curl http://localhost:8500/v1/catalog/service/consul

Here is the exception stack:
org.eclipse.persistence.exceptions.DescriptorException: 
Exception Description: This class does not define a public default constructor, or the constructor raised an exception.
Internal Exception: java.lang.InstantiationException
Descriptor: XMLDescriptor(com.orbitz.consul.model.catalog.CatalogService --> [])
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.eclipse.persistence.internal.descriptors.InstantiationPolicy.buildNewInstanceUsingDefaultConstructor(InstantiationPolicy.java:134)
	at org.eclipse.persistence.internal.descriptors.InstantiationPolicy.buildNewInstance(InstantiationPolicy.java:105)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.buildNewInstance(ObjectBuilder.java:659)
	at org.eclipse.persistence.internal.oxm.record.UnmarshalRecordImpl.initializeRecord(UnmarshalRecordImpl.java:535)
	at org.eclipse.persistence.internal.oxm.record.UnmarshalRecordImpl.initializeRecord(UnmarshalRecordImpl.java:499)
	at org.eclipse.persistence.internal.oxm.record.UnmarshalRecordImpl.startElement(UnmarshalRecordImpl.java:741)
	at org.eclipse.persistence.internal.oxm.record.json.JSONReader.parseRoot(JSONReader.java:177)
	at org.eclipse.persistence.internal.oxm.record.json.JSONReader.parseRoot(JSONReader.java:195)
	at org.eclipse.persistence.internal.oxm.record.json.JSONReader.parse(JSONReader.java:125)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:972)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:425)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:375)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:705)
	at org.eclipse.persistence.oxm.XMLUnmarshaller.unmarshal(XMLUnmarshaller.java:655)
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.unmarshal(JAXBUnmarshaller.java:301)
	at org.eclipse.persistence.jaxb.rs.MOXyJsonProvider.readFrom(MOXyJsonProvider.java:613)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:236)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:812)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:122)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:119)
	at com.orbitz.consul.util.ClientUtil.readResponse(ClientUtil.java:197)
	at com.orbitz.consul.util.ClientUtil.consulResponse(ClientUtil.java:167)
	at com.orbitz.consul.util.ClientUtil.response(ClientUtil.java:115)
	at com.orbitz.consul.util.ClientUtil.response(ClientUtil.java:79)
	at com.orbitz.consul.CatalogClient.getService(CatalogClient.java:202)
	at com.orbitz.consul.CatalogClient.getService(CatalogClient.java:161)
	at com.capitalone.chassis.refapp.ConsulClientTest.serachConsulService(ConsulClientTest.java:26)

**Comment by rickfast** [comment]
Looks like jersey isn't using Jackson to unmarshall the results. I'll have to take a look. As a workaround, can you use CXF?

**Comment by alladivasu** [comment]
I think, I can't. Let me see if I can do a PR. Will provide you more context why not CFX.

**Comment by rickfast** [comment]
Is this on your class path:

```xml
<dependency>
	<groupId>org.glassfish.jersey.media</groupId>
	<artifactId>jersey-media-json-jackson</artifactId>
	<version>2.22.1</version>
</dependency>
```

**Comment by alladivasu** [comment]
I don't have this in my classpath.

**Comment by ckstettler** [comment]
I determined what the offending dependency is.  
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-moxy</artifactId>
            <version>2.22.1</version>
        </dependency>

The moxy marshalling appears to be having issues with the immutablity of the model objects.  I have seen a couple of blogs on the topic and I want to play their solutions.

I have forked your repository but the build fails on the Immutable classes.  The code generate step does not seem to be occurring from a basic gradlew build.

Can you provide me with some build instructions?
